fix checks (#327)

diff --git a/.github/workflows/check.yaml b/.github/workflows/check.yaml
--- a/.github/workflows/check.yaml
+++ b/.github/workflows/check.yaml
@@ -20,16 +20,16 @@ jobs:
           - target: homeConfigurations.kirolsb.activationPackage
             os: ubuntu-latest
             free-space: false
-          - target: nixosConfigurations.Kirols-xps9575.config.system.toplevel
+          - target: nixosConfigurations.Kirols-xps9575.config.system.build.toplevel
             os: ubuntu-latest
             free-space: true
-          - target: nixosConfigurations.justice.config.system.toplevel
+          - target: nixosConfigurations.justice.config.system.build.toplevel
             os: ubuntu-latest
             free-space: true
-          - target: nixosConfigurations.theater.config.system.toplevel
+          - target: nixosConfigurations.theater.config.system.build.toplevel
             os: ubuntu-latest
             free-space: true
-          - target: nixosConfigurations.tang.config.system.toplevel
+          - target: nixosConfigurations.tang.config.system.build.toplevel
             os: ubuntu-24.04-arm
             free-space: false
     runs-on: ${{ matrix.os }}
@@ -64,21 +64,46 @@ jobs:
         id: build
         shell: bash
         run: |
-          echo "result=$(nix build --accept-flake-config --show-trace --print-out-paths --no-link -L '.#${{ matrix.target }}')" >> $GITHUB_OUTPUT
+          result=$(nix build --accept-flake-config --show-trace --print-out-paths --no-link -L .#${{ matrix.target }})
+          res=$?
+
+          echo "result=$result" >> $GITHUB_OUTPUT
+          if [ $res -eq 0 ]; then
+            echo "build_result=success" >> $GITHUB_OUTPUT
+          else
+            echo "build_result=failure" >> $GITHUB_OUTPUT
+            exit $res
+          fi
 
       - name: Diff profile
         id: diff
         run: |
           {
+            new_path="${{ steps.build.outputs.result }}"
+            echo "new_path=$new_path" >> $GITHUB_OUTPUT
+            old_path=$(nix eval --accept-flake-config --raw ".#${{ matrix.target }}")
+            res=$?
+            if [ $res -ne 0 ]; then
+              echo "Failed to get old path for ${{ matrix.target }}" >> $GITHUB_OUTPUT
+              exit 0
+            fi
             echo 'body<<EOF'
             echo "# ${{ matrix.target }} changes"
 
+
             nix store diff-closures --accept-flake-config --derivation \
-                "github:${{ github.repository }}/${{ github.event.before }}#${{ matrix.target }}" \
-                ".#${{ matrix.target }}" | sed 's/\x1b\[[0-9;]*m//g'
+                "$old_path" \
+                "$new_path" | sed 's/\x1b\[[0-9;]*m//g'
+            res=$?
 
             echo 'EOF'
           } >> $GITHUB_OUTPUT
+          if [ $res -eq 0 ]; then
+            echo "diff_result=success" >> $GITHUB_OUTPUT
+          else
+            echo "diff_result=failure" >> $GITHUB_OUTPUT
+            exit $res
+          fi
 
       - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71
         with:
